language: c++

matrix:
    include:
        - os: osx
          osx_image: xcode8
          compiler: clang

addons:
    homebrew:
        packages:
            - libusb-1.0

script:
    - cmake . && make
