language: c++

matrix:
    include:
    - os: osx
      osx_image: xcode10.1
      compiler: clang
    - os: osx
      osx_image: xcode8
      compiler: gcc

addons:
    homebrew:
        update: true
        brewfile: true
    apt:
        packages:
            - libusb-1.0
            
 script:
    - cmake .
    - make
