language: c++

matrix:
    include:
        - os: osx
          osx_image: xcode8
          compiler: clang

addons:
    homebrew:
        update: true
        brewfile: true
        packages:
            - libusb
            - libzip
            - zlib

script:
    - cmake . && make
