version: 1.1.{build}
image:
- Visual Studio 2017
- Ubuntu1804
configuration: Release
platform: x64
init:
- sh: >-
    sudo apt-get update

    sudo apt-get --yes --force-yes install libusb-1.0-0-dev

    sudo apt-get --yes --force-yes install libzip-dev

    sudo apt-get --yes --force-yes install libbz2-dev
    
    sudo apt-get --yes --force-yes install asciidoc

install:
- cmd: >-
    echo %APPVEYOR_BUILD_FOLDER%

    git submodule update --init

    msbuild %APPVEYOR_BUILD_FOLDER%/msvc/uuu.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    copy %PLATFORM%\%CONFIGURATION%\dll\uuu.exe %APPVEYOR_BUILD_FOLDER%\uuu.exe

    copy %PLATFORM%\%CONFIGURATION%\dll\libusb-1.0.dll %APPVEYOR_BUILD_FOLDER%\libusb-1.0.dll
build_script:
- sh: >-
    cmake .

    make
    
    git clone https://github.com/NXPmicro/mfgtools.wiki.git
    cd mfgtools.wiki
    a2x -L UUU
    
artifacts:
- path: uuu.exe
- path: uuu/uuu
- path: libusb-1.0.dll
- path: UUU.pdf

before_deploy:
- cmd: ''
deploy:
- provider: GitHub
  description: prebuild for $(APPVEYOR_REPO_COMMIT) \n\n $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: SWWVkwSfPyVIaPChBBl+uAA3Fau9Rl5iNPQ9VRL8yyggXvc6wPcr/O9iXBMVM7Ju
  artifact: uuu.exe;  libusb-1.0.dll; uuu/uuu; mfgtools.wiki/UUU.pdf
  draft: true
